# Generated by Django 3.1.2 on 2020-12-05 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('form', models.CharField(choices=[('Pills', 'Pills'), ('Powder', 'Powder')], help_text='What form is your medication', max_length=20)),
                ('dosage', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField(help_text='amount of medications to be taken')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.condition')),
            ],
        ),
    ]
