# Generated by Django 3.1.2 on 2020-12-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_condition_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(choices=[('HIV', 'HIV'), ('MALERIA', 'MALERIA')], max_length=100),
        ),
    ]
