# Generated by Django 3.1.2 on 2020-12-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201205_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(choices=[('HIV', 'HIV'), ('MALERIA', 'MALERIA')], max_length=100, unique=True),
        ),
    ]
