# Generated by Django 3.1.2 on 2020-12-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_prescription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(choices=[('mg', 'mg'), ('mcg', 'mcg'), ('g', 'g')], max_length=3),
        ),
    ]
