# Generated by Django 3.1.4 on 2021-01-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210115_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='condition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='form',
            field=models.CharField(help_text='What form is your medication', max_length=25),
        ),
    ]
